// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftRobotics.DataAccess;

#nullable disable

namespace SoftRobotics.DataAccess.Migrations
{
    [DbContext(typeof(SoftRoboticsContext))]
    partial class SoftRoboticsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SoftRobotics.Domain.RandomWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountWord")
                        .HasColumnType("int");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RandomWord", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountWord = 7,
                            Word = "AbCdEfG"
                        },
                        new
                        {
                            Id = 2,
                            CountWord = 12,
                            Word = "Test2AbCdEfG"
                        },
                        new
                        {
                            Id = 3,
                            CountWord = 13,
                            Word = "TeStUcAbCdEfG"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
